# Site settings
title: Hyper Pictogram
email: hidetoi@gmail.com
description: The architecture of accessible pictograms for humanity and machinery.
baseurl: "" # the subpath of your site, e.g. /blog/
destination: public
url: "http://pictogram.tokyo" # the base hostname & protocol for your site
twitter_username: tourinfojp
github_username:  hyperpictogram

# Build settings
markdown: kramdown

# Collections
collections:
  pictograms:
    output: true
    permalink: /pictograms/:name.html

defaults:
  -
    scope:
      path: ""
      type: "pictograms" # a collection in your site, in plural form
    values:
      layout: "pictogram"
      category: misc
